- id: '1566811891833'
  alias: Guten Morgen
  trigger:
  - platform: template
    value_template: '{{ states(''sensor.time'') == (states.input_datetime.wakeup_time.attributes.timestamp
      | int | timestamp_custom(''%H:%M'', False)) }}'
  condition:
  - condition: state
    entity_id: input_boolean.wakeup_enabled
    state: 'on'
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  action:
  - data:
      brightness_pct: '1'
      entity_id: light.bett_1
      transition: '900'
    service: light.turn_on
  - data:
      brightness_pct: '1'
      entity_id: light.bett_2
      transition: '900'
    service: light.turn_on
  - delay: 00:00:05
  - data:
      brightness_pct: '100'
      entity_id: light.bett_1
      transition: '900'
    service: light.turn_on
  - data:
      brightness_pct: '100'
      entity_id: light.bett_2
      transition: '900'
    service: light.turn_on
  mode: single
- id: '1566810704743'
  alias: Voland Start
  trigger:
  - at: '12:00:00'
    platform: time
  - at: 08:30:00
    platform: time
  condition:
  - condition: and
    conditions:
    - condition: template
      value_template: '{{ states.vacuum.voland.attributes.battery_level > 95 }}'
    - condition: template
      value_template: '{{ states.vacuum.voland.attributes.status == ''Charging'' }}'
    - condition: time
      weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
  action:
  - service: vacuum.start_pause
    data:
      entity_id: vacuum.voland
  - service: notify.telegram_all
    data:
      message: Voland started cleaning
- id: '1569526048860'
  alias: Voland Finish
  trigger:
  - platform: template
    value_template: '{{ states.vacuum.voland.attributes.status == ''Docking - End
      Mission'' }}'
  condition: []
  action:
  - data:
      message: Voland finished successfully his task
    service: notify.telegram_all
  mode: single
- id: '1569526121970'
  alias: Voland Stuck
  trigger:
    platform: template
    value_template: '{{ states.vacuum.voland.attributes.status == ''Stuck'' }}'
  condition: []
  action:
  - data:
      message: Attention! Voland is stuck
    service: notify.telegram_all
- id: Hass Startup Notification
  alias: Hass Startup Notification
  trigger:
  - event: start
    platform: homeassistant
  action:
  - data:
      message: Home assistant is ready
    service: notify.mikhail
  mode: single
- id: Hass Shutdown Notification
  alias: Hass Shutdown Notification
  trigger:
  - event: shutdown
    platform: homeassistant
  action:
  - data:
      message: Home Assistant is turning off
    service: notify.mikhail
  mode: single
- alias: System - New device connected
  trigger:
  - platform: event
    event_type: device_tracker_new_device
  action:
  - service: notify.mikhail
    data_template:
      message: 'New device: {{trigger.event.data.host_name}} ({{trigger.event.data.entity_id}})'
  id: a134261637734eb4b588ee9532a49983
- id: '1604230060346'
  alias: '[Light] Girlande ON '
  description: ''
  trigger:
  - platform: sun
    event: sunset
    offset: +00:15:01
  condition:
  - condition: state
    entity_id: person.mikhail
    state: home
  action:
  - type: turn_on
    device_id: 708d76eb1fe44d83a89ab518c22974c4
    entity_id: switch.terasse
    domain: switch
  - type: turn_on
    device_id: 1fcc43855c3b1ab80f148eb45140564c
    entity_id: switch.erkerlicht
    domain: switch
  mode: single
- id: '1604230116420'
  alias: '[Light] Girlande OFF'
  description: ''
  trigger:
  - platform: time
    at: '22:30:00'
  condition: []
  action:
  - type: turn_off
    device_id: 708d76eb1fe44d83a89ab518c22974c4
    entity_id: switch.terasse
    domain: switch
  - type: turn_off
    device_id: 1fcc43855c3b1ab80f148eb45140564c
    entity_id: switch.erkerlicht
    domain: switch
  mode: single
- id: '1605357001631'
  alias: Notify about new version of HA
  description: Send message to TG if new version available
  trigger:
  - platform: state
    entity_id: binary_sensor.updater
    attribute: newest_version
  condition: []
  action:
  - service: notify.mikhail
    data:
      message: 'New version of HA is available: {{states.binary_sensor.updater.attributes["newest_version"]}}'
  mode: single
- id: '1606589026283'
  alias: '[Heizung] Esszimmer daily OFF v3'
  description: Turn off after heating for 15 minutes
  trigger:
  - platform: state
    entity_id: climate.comet_sofa
    attribute: preset_mode
    to: comfort
    for: 00:17:00
  condition:
  - condition: time
    after: 08:00
    before: '20:30'
  action:
  - device_id: 31792eee80ff46949b3deece3393623b
    domain: climate
    entity_id: climate.comet_sofa
    type: set_hvac_mode
    hvac_mode: 'off'
  mode: single
- id: '1606733115402'
  alias: '[Heizung] Esszimmer Morning Heatup ON'
  description: Every morning if temperature below 23
  trigger:
  - platform: time_pattern
    minutes: '30'
    seconds: '0'
    hours: '6'
  condition:
  - condition: template
    value_template: "{{ (state_attr(\"climate.comet_sofa\",\"current_temperature\"\
      ) | float) < \n(states(\"input_number.ez_temperature\")|float)}}"
  - condition: state
    entity_id: sensor.tado_wz_tado_mode
    state: HOME
  action:
  - device_id: 31792eee80ff46949b3deece3393623b
    domain: climate
    entity_id: climate.comet_sofa
    type: set_preset_mode
    preset_mode: comfort
  mode: single
- id: '1606733169293'
  alias: '[Heizung] Esszimmer Morning Heatup OFF'
  description: Every morning at 07:00 (after 0:30 hour of heating)
  trigger:
  - platform: time_pattern
    seconds: '0'
    hours: '7'
    minutes: '0'
  condition:
  - condition: state
    entity_id: climate.comet_sofa
    state: comfort
    attribute: preset_mode
  action:
  - device_id: 31792eee80ff46949b3deece3393623b
    domain: climate
    entity_id: climate.comet_sofa
    type: set_hvac_mode
    hvac_mode: 'off'
  mode: single
- id: '1606994370956'
  alias: '[Heizung] Esszimmer daily ON v2'
  description: Every hour if temperature below 22
  trigger:
  - platform: numeric_state
    entity_id: climate.comet_sofa
    attribute: current_temperature
    for: 00:02:00
    below: '21'
  condition:
  - condition: time
    after: 08:00:00
    before: '20:00:00'
  - condition: state
    entity_id: climate.comet_sofa
    state: eco
    attribute: preset_mode
  - condition: state
    entity_id: climate.tado_wz
    state: home
    attribute: preset_mode
  action:
  - device_id: 31792eee80ff46949b3deece3393623b
    domain: climate
    entity_id: climate.comet_sofa
    type: set_preset_mode
    preset_mode: comfort
  mode: single
- id: '1607432666064'
  alias: '[Location] MM Not home'
  description: ''
  trigger:
  - platform: state
    entity_id: person.mikhail
    from: home
    for: 00:03:00
    to: not_home
  condition:
  - condition: time
    after: 07:00
    before: '23:00'
  action:
  - service: notify.mikhail
    data:
      message: Mikhail not home!
  - device_id: 5aaa960dfc7982231474b67b2334b732
    domain: climate
    entity_id: climate.tado_wz
    type: set_preset_mode
    preset_mode: away
  - service: script.turn_all_devices_except_aqua
    data: {}
  mode: single
- id: '1607601840328'
  alias: '[Aqua] 30, 120: ON'
  description: ''
  trigger:
  - platform: time
    at: '10:00:00'
  condition: []
  action:
  - service: homeassistant.turn_on
    data: {}
    entity_id: group.ha_aqua_120
  - service: homeassistant.turn_on
    data: {}
    target:
      device_id: 8c09b9f85aa9413aba7307c5eeb5eeef
  mode: single
- id: '1607601893611'
  alias: '[Aqua] 30, 120: OFF'
  description: ''
  trigger:
  - platform: time
    at: '22:00:00'
  condition: []
  action:
  - service: homeassistant.turn_off
    data: {}
    entity_id: group.ha_aqua_120
  - service: homeassistant.turn_off
    data: {}
    target:
      device_id: 8c09b9f85aa9413aba7307c5eeb5eeef
  mode: single
- id: '1607707348335'
  alias: '[Location] MM Returned home '
  description: ''
  trigger:
  - platform: state
    entity_id: person.mikhail
    from: not_home
    for: 00:01:00
    to: home
  condition:
  - condition: time
    after: 07:00
    before: '23:00'
  action:
  - service: notify.mikhail
    data:
      message: Mikhail returned home!
  - device_id: 5aaa960dfc7982231474b67b2334b732
    domain: climate
    entity_id: climate.tado_wz
    type: set_preset_mode
    preset_mode: home
  - device_id: 5aaa960dfc7982231474b67b2334b732
    domain: climate
    entity_id: climate.tado_wz
    type: set_hvac_mode
    hvac_mode: auto
  mode: single
- id: '1608464180046'
  alias: '[Heizung] WZ: Windows were opened'
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.tado_wz_open_window
    from: 'off'
    to: 'on'
  condition:
  - condition: device
    device_id: 5aaa960dfc7982231474b67b2334b732
    domain: climate
    entity_id: climate.tado_wz
    type: is_hvac_mode
    hvac_mode: auto
  action:
  - device_id: 5aaa960dfc7982231474b67b2334b732
    domain: climate
    entity_id: climate.tado_wz
    type: set_hvac_mode
    hvac_mode: 'off'
  - service: notify.mikhail
    data:
      message: Windows were opened, TADO in OFF mode
  mode: single
- id: '1608464212614'
  alias: '[Heizung] WZ: Windows were closed'
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.tado_wz_open_window
    from: 'on'
    to: 'off'
  condition:
  - condition: device
    device_id: 5aaa960dfc7982231474b67b2334b732
    domain: climate
    entity_id: climate.tado_wz
    type: is_hvac_mode
    hvac_mode: auto
  action:
  - device_id: 5aaa960dfc7982231474b67b2334b732
    domain: climate
    entity_id: climate.tado_wz
    type: set_hvac_mode
    hvac_mode: auto
  - service: notify.mikhail
    data:
      message: Windows were closed, TADO in Auto mode
  mode: single
- id: '1609419383548'
  alias: '[Heizung] EZ daily ON v4'
  description: Turn heating  in EZ on, if temperature <= X
  trigger:
  - platform: time_pattern
    hours: '*'
    seconds: '0'
    minutes: /1
  condition:
  - condition: time
    after: 08:00:00
    before: '20:00:00'
  - condition: state
    entity_id: input_boolean.heizung_ez
    state: 'on'
  - condition: state
    entity_id: climate.tado_wz
    state: home
    attribute: preset_mode
  - condition: template
    value_template: '{{ (state_attr("climate.comet_sofa","current_temperature") |
      float) <=

      (states("input_number.ez_temperature")|float-0.5)}}'
  - condition: state
    entity_id: climate.comet_sofa
    state: 'off'
  action:
  - service: climate.turn_on
    data: {}
    entity_id: climate.comet_sofa
  - device_id: 31792eee80ff46949b3deece3393623b
    domain: climate
    entity_id: climate.comet_sofa
    type: set_preset_mode
    preset_mode: comfort
  - service: notify.mikhail
    data:
      message: EZ Heizung is ON
  mode: single
- id: '1609421084881'
  alias: '[Heizung] EZ daily OFF v4'
  description: Turn heating  in EZ off, if temperature >= X+0.5
  trigger:
  - platform: time_pattern
    hours: '*'
    minutes: /2
    seconds: '30'
  condition:
  - condition: time
    after: 08:00
    before: '20:30'
  - condition: state
    entity_id: input_boolean.heizung_ez
    state: 'on'
  - condition: template
    value_template: '{{ (state_attr("climate.comet_sofa","current_temperature") |
      float) >=

      (states("input_number.ez_temperature")|float )}}'
  - condition: state
    entity_id: climate.comet_sofa
    state: heat
  action:
  - device_id: 31792eee80ff46949b3deece3393623b
    domain: climate
    entity_id: climate.comet_sofa
    type: set_hvac_mode
    hvac_mode: 'off'
  - service: notify.mikhail
    data:
      message: EZ Heizung is OFF
  mode: single
- id: '1613678701386'
  alias: '[Light] Turn Light in SZ Off'
  description: 2h after sunrise
  trigger:
  - platform: sun
    event: sunrise
    offset: 02:30:00
  condition: []
  action:
  - service: light.turn_off
    data: {}
    entity_id: light.hue_sz
  - service: notify.mikhail
    data:
      message: Light in SZ turned off
  mode: single
